const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const Prescription = require('../models/Prescription');
const { protect } = require('../middleware/auth');

// Doctor creates prescription
router.post('/', protect, async (req, res) => {
    try {
        const { appointmentId, patientId, medicines, diagnosis, notes } = req.body;
        const prescription = await Prescription.create({
            appointment: appointmentId,
            doctor: req.user._id,
            patient: patientId,
            medicines,
            diagnosis,
            notes
        });
        res.status(201).json(prescription);
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
});

// Fetch prescription by appointmentId
router.get('/appointment/:appointmentId', protect, async (req, res) => {
    try {
        const p = await Prescription.findOne({ appointment: req.params.appointmentId })
            .populate('doctor', 'name')
            .populate('patient', 'name');
        if (!p) return res.status(404).json({ message: 'No prescription found' });
        res.json(p);
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
});

// Download prescription as PDF
router.get('/:id/pdf', protect, async (req, res) => {
    try {
        const p = await Prescription.findById(req.params.id)
            .populate('doctor', 'name email')
            .populate('patient', 'name email');
        if (!p) return res.status(404).json({ message: 'Not found' });

        const doc = new PDFDocument({ margin: 50 });
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=prescription_${p._id}.pdf`);
        doc.pipe(res);

        // Header
        doc.fontSize(22).fillColor('#0a5c45').text('HealthAI — Digital Prescription', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(10).fillColor('grey').text(`Date: ${new Date(p.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, { align: 'center' });
        doc.moveDown(1);
        doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#00d4aa').stroke();
        doc.moveDown(1);

        // Doctor & Patient Info
        doc.fontSize(12).fillColor('black').text(`Doctor: Dr. ${p.doctor?.name}`);
        doc.text(`Patient: ${p.patient?.name}`);
        doc.moveDown(0.5);
        if (p.diagnosis) {
            doc.fontSize(11).fillColor('#333').text(`Diagnosis: ${p.diagnosis}`);
            doc.moveDown(0.5);
        }

        // Medicines table
        doc.fontSize(13).fillColor('#0a5c45').text('Prescribed Medicines:', { underline: true });
        doc.moveDown(0.5);
        p.medicines.forEach((med, i) => {
            doc.fontSize(11).fillColor('black').text(`${i + 1}. ${med.name}`);
            if (med.dosage) doc.fontSize(10).fillColor('#555').text(`   Dosage: ${med.dosage}`);
            if (med.frequency) doc.fontSize(10).fillColor('#555').text(`   Frequency: ${med.frequency}`);
            if (med.duration) doc.fontSize(10).fillColor('#555').text(`   Duration: ${med.duration}`);
            doc.moveDown(0.3);
        });

        if (p.notes) {
            doc.moveDown(0.5);
            doc.fontSize(11).fillColor('black').text(`Additional Notes: ${p.notes}`);
        }

        doc.moveDown(2);
        doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ccc').stroke();
        doc.moveDown(0.5);
        doc.fontSize(9).fillColor('grey').text('Generated by HealthAI — For medical use only. Consult your doctor before changing medications.', { align: 'center' });

        doc.end();
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
});

module.exports = router;
