const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const Groq = require('groq-sdk');
const SymptomCheck = require('../models/SymptomCheck');
const { protect } = require('../middleware/auth');

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

router.get('/generate', protect, async (req, res) => {
    try {
        const history = await SymptomCheck.find({ user: req.user._id }).sort({ createdAt: -1 }).limit(20);

        if (!history.length) {
            return res.status(400).json({ message: 'No symptom history found to generate report.' });
        }

        const summaryData = history.map(h => ({
            date: new Date(h.createdAt).toLocaleDateString(),
            symptoms: h.symptoms.join(', '),
            specialist: h.recommendedSpecialist,
            severity: h.severity,
        }));

        const prompt = `You are a professional medical AI summarizer. Below is a patient's symptom check history.
Based on this, write a brief, structured Health Summary Report in 3 sections:
1. Overall Health Trend (2-3 sentences)
2. Recurring Issues (bullet points of patterns you notice)
3. Recommendations (2-3 actionable health tips)

Patient History:
${JSON.stringify(summaryData, null, 2)}

Keep it professional, concise, and clear. Do NOT use JSON format. Write in plain paragraphs.`;

        const completion = await groq.chat.completions.create({
            messages: [{ role: 'user', content: prompt }],
            model: 'llama-3.3-70b-versatile',
            temperature: 0.4,
            max_tokens: 600,
        });

        const reportText = completion.choices[0]?.message?.content || 'Unable to generate report.';

        // Generate PDF
        const doc = new PDFDocument({ margin: 50 });
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=health_report_${req.user._id}.pdf`);
        doc.pipe(res);

        // Header
        doc.fontSize(22).fillColor('#0a5c45').text('HealthAI — Monthly Health Report', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(10).fillColor('grey').text(`Patient: ${req.user.name}  |  Generated: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, { align: 'center' });
        doc.moveDown(1);
        doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#00d4aa').stroke();
        doc.moveDown(1);

        // AI Report Content
        doc.fontSize(12).fillColor('#111').text(reportText, { lineGap: 6 });

        doc.moveDown(2);
        doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#ccc').stroke();
        doc.moveDown(0.5);

        // Symptom History Table
        doc.fontSize(13).fillColor('#0a5c45').text('Symptom Check History', { underline: true });
        doc.moveDown(0.5);
        history.forEach((h, i) => {
            doc.fontSize(10).fillColor('black').text(`${i + 1}. [${new Date(h.createdAt).toLocaleDateString()}] — ${h.symptoms.join(', ')}`);
            if (h.recommendedSpecialist) doc.fontSize(9).fillColor('#555').text(`   → Specialist: ${h.recommendedSpecialist}  | Severity: ${h.severity}`);
            doc.moveDown(0.2);
        });

        doc.moveDown(1.5);
        doc.fontSize(9).fillColor('grey').text('Generated by HealthAI AI Health Report Generator. Not a substitute for professional medical advice.', { align: 'center' });
        doc.end();
    } catch (err) {
        console.error('Report error:', err.message);
        res.status(500).json({ message: err.message });
    }
});

module.exports = router;
